spring:
    application:
        name: websocket
    data:
        mongodb:
            uri: ${MONGODB_URI}
            database: chat_app
server:
    port: ${SERVER_PORT:8088}
websocket:
    jwt:
        secret: ${JWT_SECRET}
        expirationMs: 86400000